
# rocketmq ?????? RocketMQProperties ???
rocketmq:
  name-server: 192.168.10.129:9876 # RocketMQ Namesrv
  # Producer ???
  producer:
    group: demo-producer-group # ?????
    send-message-timeout: 3000 # ?????????????????? 3000 ?
    compress-message-body-threshold: 4096 # ??????????????????????????????? 4 * 1024B
    max-message-size: 4194304 # ??????????????? 4 * 1024 * 1024B
    retry-times-when-send-failed: 2 # ?????????????????? 2 ??
    retry-times-when-send-async-failed: 2 # ?????????????????? 2 ??
    retry-next-server: false # ????? Broker ????????????????? Broker ???? false
    access-key: # Access Key ???? https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md ??
    secret-key: # Secret Key
    enable-msg-trace: true # ?????????????? true ?????? https://github.com/apache/rocketmq/blob/master/docs/cn/msg_trace/user_guide.md ??
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # ???????? Topic ???? RMQ_SYS_TRACE_TOPIC ?
  # Consumer ???
  consumer:
    listeners: # ??????????????? Topic ???? Map<?????, <Topic, Boolean>> ???????????????
      test-consumer-group:
        topic1: false # ?? test-consumer-group ? topic1 ?????
server:
  port: 8090
