# web服务访问端口
server:
  port: 8080

#langchain4j测试模型
langchain4j:
  open-ai:
    chat-model:
#      api-key: demo   #openAI
#      model-name: gpt-4o-mini
#      base-url: http://langchain4j.dev/demo/openai/v1
      log-requests: true #请求和响应日志
      log-responses: true
      base-url: https://api.deepseek.com  # deepseek
      api-key: ${DEEP_SEEK_API_KEY} #
      model-name: deepseek-chat

      streaming-enabled: true
      streaming-completion-token-limit: 1024  # 最大token数
      streaming-timeout: 30s  # 流式响应超时时间
      streaming-buffer-size: 50  # 缓冲区大小

#MongoDB连接配置
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db

#启用日志debug级别
logging:
  level:
    root: debug