spring:
  # ShardingSphere 配置项
  shardingsphere:
    #打印SQL
    props:
      sql-show: true
    # 数据源配置
    datasource:
      # 所有数据源的名字
      names: ds-master, ds-slave-1, ds-slave-2
      # 订单 orders 主库的数据源配置
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test_orders?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
      # 订单 orders 从库数据源配置
      ds-slave-1:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test_orders_01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
      # 订单 orders 从库数据源配置
      ds-slave-2:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test_orders_02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root

    rules:
      # 读写分离配置
      readwrite-splitting:
        data-sources:
          myds: #读写分离逻辑数据源名称
            type: Static #读写分离类型，比如：Static，Dynamic
            props:
              write-data-source-name: ds-master  #写库数据源名称
              read-data-source-names: ds-slave-1, ds-slave-2 #读库数据源名称，多个从数据源用逗号分隔
            load-balancer-name: round #负载均衡算法名称
        # 负载均衡算法配置
        load-balancers:
          round: #负载均衡算法名称
            type: ROUND_ROBIN #负载均衡算法类型

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: cn.elevencc.springboot.datasource.pojo # 配置数据库实体包路径
